### ISSUE TITLE
Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/fontZoom/fontZoom'

### ISSUE THREAD

**Issue by rodrigooler** [RebirthDB/rebirthdb-desktop#44]
The following error is occurring when using npm to install dependencies instead of yarn

```bash
MacBook-Pro-de-Rodrigo:rebirthdb-desktop rodrigooler$ npm run dev

> rebirthdb-desktop@1.0.0 dev /Users/rodrigooler/projects/rebirthdb-desktop
> cross-env START_HOT=1 cross-env START_HOT=1 npm run start-renderer-dev


> rebirthdb-desktop@1.0.0 start-renderer-dev /Users/rodrigooler/projects/rebirthdb-desktop
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --mode development --config webpack.config.dev.js

/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/webpack-dev-server/bin/webpack-dev-server.js:343
    throw err;
    ^

Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/fontZoom/fontZoom'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at resolveMonacoPath (/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/monaco-editor-webpack-plugin/index.js:21:18)
    at use.options.pre.featurePaths.map (/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/monaco-editor-webpack-plugin/index.js:107:51)
    at Array.map (<anonymous>)
    at createLoaderRules (/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/monaco-editor-webpack-plugin/index.js:107:31)
    at MonacoWebpackPlugin.apply (/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/monaco-editor-webpack-plugin/index.js:50:19)
    at webpack (/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/webpack/lib/webpack.js:37:12)
    at startDevServer (/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/webpack-dev-server/bin/webpack-dev-server.js:335:16)
    at processOptions (/Users/rodrigooler/projects/rebirthdb-desktop/node_modules/webpack-dev-server/bin/webpack-dev-server.js:309:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rebirthdb-desktop@1.0.0 start-renderer-dev: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --mode development --config webpack.config.dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rebirthdb-desktop@1.0.0 start-renderer-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rodrigooler/.npm/_logs/2018-09-06T04_48_45_100Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rebirthdb-desktop@1.0.0 dev: `cross-env START_HOT=1 cross-env START_HOT=1 npm run start-renderer-dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rebirthdb-desktop@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rodrigooler/.npm/_logs/2018-09-06T04_48_45_137Z-debug.log
MacBook-Pro-de-Rodrigo:rebirthdb-desktop rodrigooler$ 
```
![captura de tela 2018-09-06 as 01 48 58](https://user-images.githubusercontent.com/5496931/45135684-123cd000-b177-11e8-9e81-90bed6c7cf48.png)

**Comment by DMXL** [comment]
Hey how far along are you with this issue? Just came across this from another project, and happened to have found out that it's the incompatibility of the `monaco-editor-webpack-plugin`. In my case I let it fallback to `v0.14.0` and the error is gone. FYI my `monaco-editor` is at `v0.13.*`. Hope this'd help!

**Comment by chinchang** [comment]
Getting same error.

@DMXL Did you fix it by using Monaco@0.14.0?

**Comment by DMXL** [comment]
> Getting same error.
> 
> @DMXL Did you fix it by using Monaco@0.14.0?

@chinchang No I meant the webpack plugin is `v.0.14.0`, and **monaco** is `v.0.13.1`.

**Comment by sagivf** [comment]
@rodrigooler can we close this?
